name: Frontend Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: yarn install

      - name: Build React app
        run: CI=false yarn build

      - name: Decode PEM KEY & Access EC2
        run: |
          echo "$EC2_KEY" | base64 -d > FinishLine-Server.pem
          chmod 600 FinishLine-Server.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Setting Permission
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: sudo chown -R ${{ secrets.EC2_User }}:${{ secrets.EC2_USER }} ${{ secrets.DEPLOY_PATH }}
        
      - name: Update build files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "build/*"
          target: "/home/ubuntu/build"

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: "sudo systemctl restart nginx"
    
      
